// apps/web/src/components/Dartboard.vue
<!--
  The board, drawn from the same millimetre geometry the autoscorer uses.

  Tapping it records where the dart landed, not just what it scored, which is
  what the positional statistics in docs/04-stats.md are built on. The SVG
  user space *is* board space (millimetres, origin at the bull, y flipped for
  the screen), so a tap converts to a position with no magic numbers.

  Precision on a phone is the whole problem here. A treble bed is 8 mm wide —
  about six pixels on a phone, and entirely hidden under a fingertip. So the
  board works like a text cursor on a touchscreen: press, and a magnifying lens
  appears *offset from the finger* showing the board underneath at three times
  the size with a crosshair on the exact point; drag to adjust; lift to score.
-->
<script setup lang="ts">
import { BOARD, formatHit, scoreAt, targetPoint, type Hit, type Point } from '@treblewise/core';
import { computed, ref, useId } from 'vue';

import { COLOURS, LENS, R, boardPointAt, buildBeds, numberPositions, placeLens } from './dartboardGeometry.js';

export interface BoardDart {
  id: string;
  hit: Hit;
  pos?: Point;
  /** Dimmed, for darts from earlier visits. */
  past?: boolean;
}

const props = withDefaults(
  defineProps<{
    darts?: BoardDart[];
    /** Drawn as a ring, to show where a checkout route says to aim. */
    target?: Hit | null;
    disabled?: boolean;
    /** Taps score: off, the board is a picture of where darts landed. */
    interactive?: boolean;
    /**
     * Drawn as a picture and nothing else: no taps, no lens, nothing for a
     * screen reader. The landing page uses it as its backdrop, where its size
     * and motion come from the element around it.
     */
    decorative?: boolean;
  }>(),
  { darts: () => [], target: null, disabled: false, interactive: false, decorative: false },
);

const emit = defineEmits<{ hit: [hit: Hit, pos: Point] }>();

const beds = buildBeds();
const numbers = numberPositions();

// Ids have to be unique per instance: two boards on one page would otherwise
// share a lens clip and magnify each other.
const uid = useId().replace(/[^a-zA-Z0-9-]/g, '');
const artId = `board-${uid}`;
const dartsId = `darts-${uid}`;
const clipId = `lens-${uid}`;

const svg = ref<SVGSVGElement | null>(null);
const preview = ref<{ pos: Point; hit: Hit } | null>(null);
const scoring = computed(() => props.interactive && !props.disabled && !props.decorative);

function positionOf(event: PointerEvent): Point | null {
  return svg.value ? boardPointAt(svg.value.getBoundingClientRect(), event.clientX, event.clientY) : null;
}

function track(event: PointerEvent) {
  if (!scoring.value) return;
  const pos = positionOf(event);
  if (!pos) return;
  const hit = scoreAt(pos);
  const current = preview.value;
  // A short tick whenever the score under the finger changes: on a phone
  // that lands before the eye has read the lens.
  if (current === null || current.hit.value !== hit.value || current.hit.ring !== hit.ring) navigator.vibrate?.(6);
  preview.value = { pos, hit };
}

function down(event: PointerEvent) {
  if (props.decorative) return;
  (event.currentTarget as SVGSVGElement).setPointerCapture?.(event.pointerId);
  track(event);
}

function move(event: PointerEvent) {
  if (preview.value) track(event);
}

function commit(event: PointerEvent) {
  if (!scoring.value) return;
  const pos = positionOf(event) ?? preview.value?.pos;
  preview.value = null;
  if (pos) emit('hit', scoreAt(pos), pos);
}

const targetPos = computed(() => (props.target && props.target.ring !== 'miss' ? targetPoint(props.target) : null));

// The finger's point and the lens, both in SVG coordinates.
const finger = computed(() => (preview.value ? { x: preview.value.pos.x, y: -preview.value.pos.y } : null));
const lens = computed(() => (finger.value ? placeLens(finger.value) : null));
const lensTransform = computed(() =>
  finger.value && lens.value
    ? `translate(${lens.value.cx} ${lens.value.cy}) scale(${LENS.magnification}) translate(${-finger.value.x} ${-finger.value.y})`
    : '',
);
</script>

<template>
  <svg
    ref="svg"
    :class="decorative ? undefined : 'dartboard'"
    :viewBox="`${-R} ${-R} ${2 * R} ${2 * R}`"
    :role="decorative ? undefined : interactive ? 'button' : 'img'"
    :aria-label="decorative ? undefined : 'Dartboard'"
    :aria-hidden="decorative || undefined"
    @pointerdown="down"
    @pointermove="move"
    @pointerup="commit"
    @pointercancel="preview = null"
  >
    <defs>
      <g :id="artId">
        <circle :cx="0" :cy="0" :r="R" :fill="COLOURS.surround" />
        <g :stroke="COLOURS.wire" :stroke-width="0.8">
          <path v-for="b in beds" :key="b.key" :d="b.d" :fill="b.fill" />
          <circle :cx="0" :cy="0" :r="BOARD.outerBullRadius" :fill="COLOURS.green" />
          <circle :cx="0" :cy="0" :r="BOARD.bullRadius" :fill="COLOURS.red" />
        </g>
        <!-- A backdrop turns: numbers going round upside down are noise. -->
        <g v-if="!decorative" :fill="COLOURS.number" :font-size="26" font-weight="600" text-anchor="middle">
          <text v-for="n in numbers" :key="n.sector" :x="n.x" :y="n.y + 9">{{ n.sector }}</text>
        </g>
      </g>

      <g :id="dartsId">
        <template v-for="(dart, index) in darts" :key="dart.id">
          <g v-if="dart.pos" :opacity="dart.past ? 0.35 : 1">
            <circle :cx="dart.pos.x" :cy="-dart.pos.y" :r="7" :fill="COLOURS.marker" :stroke="COLOURS.ink" :stroke-width="2" />
            <text :x="dart.pos.x" :y="-dart.pos.y + 4" :fill="COLOURS.ink" :font-size="11" font-weight="700" text-anchor="middle">
              {{ index + 1 }}
            </text>
          </g>
        </template>
      </g>

      <clipPath v-if="lens" :id="clipId">
        <circle :cx="lens.cx" :cy="lens.cy" :r="LENS.radius" />
      </clipPath>
    </defs>

    <use :href="`#${artId}`" />

    <circle
      v-if="targetPos"
      class="dartboard-target"
      :cx="targetPos.x"
      :cy="-targetPos.y"
      :r="9"
      fill="none"
      :stroke="COLOURS.ink"
      :stroke-width="2.5"
    />

    <use :href="`#${dartsId}`" />

    <g v-if="preview && finger && lens" class="dartboard-lens" pointer-events="none">
      <!-- Where the finger actually is, left visible under the lens. -->
      <circle :cx="finger.x" :cy="finger.y" :r="12" fill="none" :stroke="COLOURS.ink" :stroke-width="1.6" :opacity="0.9" />
      <circle :cx="finger.x" :cy="finger.y" :r="2" :fill="COLOURS.ink" />

      <circle :cx="lens.cx" :cy="lens.cy" :r="LENS.radius + 3" :fill="COLOURS.surround" :stroke="COLOURS.ink" :stroke-width="3" />

      <g :clip-path="`url(#${clipId})`">
        <use :href="`#${artId}`" :transform="lensTransform" />
        <use :href="`#${dartsId}`" :transform="lensTransform" />

        <!-- The crosshair sits at the lens centre, which is the finger's exact
             point magnified: the whole purpose of the thing. -->
        <g :stroke="COLOURS.ink" :stroke-width="1.8" :opacity="0.95">
          <line :x1="lens.cx - LENS.radius" :y1="lens.cy" :x2="lens.cx - 9" :y2="lens.cy" />
          <line :x1="lens.cx + 9" :y1="lens.cy" :x2="lens.cx + LENS.radius" :y2="lens.cy" />
          <line :x1="lens.cx" :y1="lens.cy - LENS.radius" :x2="lens.cx" :y2="lens.cy - 9" />
          <line :x1="lens.cx" :y1="lens.cy + 9" :x2="lens.cx" :y2="lens.cy + LENS.radius" />
        </g>
        <circle :cx="lens.cx" :cy="lens.cy" :r="3.5" fill="none" :stroke="COLOURS.ink" :stroke-width="1.8" />

        <rect :x="lens.cx - 34" :y="lens.cy + LENS.radius - 30" :width="68" :height="26" :rx="8" :fill="COLOURS.plate" />
        <text :x="lens.cx" :y="lens.cy + LENS.radius - 11" :fill="COLOURS.ink" :font-size="19" font-weight="700" text-anchor="middle">
          {{ formatHit(preview.hit) }}
        </text>
      </g>
    </g>
  </svg>
</template>

// apps/web/src/components/Dartboard.tsx
/**
 * The board, drawn from the same millimetre geometry the autoscorer uses.
 *
 * Tapping it records where the dart landed, not just what it scored, which is
 * what the positional statistics in `docs/04-stats.md` are built on. The SVG
 * user space *is* board space (millimetres, origin at the bull, y flipped for
 * the screen), so a tap converts to a position with no magic numbers.
 *
 * Precision on a phone is the whole problem here. A treble bed is 8 mm wide —
 * about six pixels on a phone, and entirely hidden under a fingertip. So the
 * board works like a text cursor on a touchscreen: press, and a magnifying lens
 * appears *offset from the finger* showing the board underneath at three times
 * the size with a crosshair on the exact point; drag to adjust; lift to score.
 */

import {
  BOARD,
  SECTORS,
  formatHit,
  scoreAt,
  sectorAngle,
  targetPoint,
  type Hit,
  type Point,
} from '@treblewise/core';
import { useId, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';

const R = BOARD.boardRadius;
const HALF_SECTOR = 9;

/** Lens geometry, in board millimetres. */
const LENS = {
  radius: 58,
  magnification: 3.2,
  /** How far the lens sits from the finger: clear of a fingertip, still close. */
  offset: 96,
};

/** The board's colours live in global.css, with the rest of the palette. */
const COLOURS = {
  surround: 'var(--board-surround)',
  dark: 'var(--board-black)',
  light: 'var(--board-beige)',
  red: 'var(--board-red)',
  green: 'var(--board-green)',
  wire: 'var(--board-wire)',
  number: 'var(--board-number)',
  marker: 'var(--dart-marker)',
  ink: 'var(--mark-ink)',
  plate: 'var(--mark-shade-strong)',
};

const rad = (deg: number) => (deg * Math.PI) / 180;

/** A point in SVG space: board millimetres with the y axis flipped. */
function svgPoint(r: number, deg: number): string {
  return `${(r * Math.cos(rad(deg))).toFixed(2)},${(-r * Math.sin(rad(deg))).toFixed(2)}`;
}

/** The ring segment between two radii and two angles (angles anticlockwise). */
function bed(r1: number, r2: number, from: number, to: number): string {
  return [
    `M ${svgPoint(r2, from)}`,
    `A ${r2} ${r2} 0 0 0 ${svgPoint(r2, to)}`,
    `L ${svgPoint(r1, to)}`,
    `A ${r1} ${r1} 0 0 1 ${svgPoint(r1, from)}`,
    'Z',
  ].join(' ');
}

interface Bed {
  key: string;
  d: string;
  fill: string;
}

function buildBeds(): Bed[] {
  const beds: Bed[] = [];

  SECTORS.forEach((sector, index) => {
    const centre = sectorAngle(sector);
    const from = centre - HALF_SECTOR;
    const to = centre + HALF_SECTOR;
    const isDark = index % 2 === 0;
    const single = isDark ? COLOURS.dark : COLOURS.light;
    const ring = isDark ? COLOURS.red : COLOURS.green;

    beds.push(
      { key: `s-in-${sector}`, d: bed(BOARD.outerBullRadius, BOARD.trebleInnerRadius, from, to), fill: single },
      { key: `t-${sector}`, d: bed(BOARD.trebleInnerRadius, BOARD.trebleOuterRadius, from, to), fill: ring },
      { key: `s-out-${sector}`, d: bed(BOARD.trebleOuterRadius, BOARD.doubleInnerRadius, from, to), fill: single },
      { key: `d-${sector}`, d: bed(BOARD.doubleInnerRadius, BOARD.doubleOuterRadius, from, to), fill: ring },
    );
  });

  return beds;
}

export interface LensPlacement {
  cx: number;
  cy: number;
}

/**
 * Where to put the lens: directly above the finger, always, with no exceptions.
 *
 * An earlier version moved it sideways near the top of the board and below it
 * in the corners, to keep the whole lens inside the board's frame. That was
 * worse than the problem: crossing the 20 made it jump from one side to the
 * other, and a lens you have to re-find with your eyes is not a lens.
 *
 * So it never moves relative to the finger, and is allowed to float past the
 * edge of the board instead — the SVG is `overflow: visible` — exactly as a
 * phone's text loupe floats over whatever happens to be above it.
 *
 * Works in SVG coordinates, so "above" means a smaller y.
 */
export function placeLens(
  point: { x: number; y: number },
  offset = LENS.offset,
): LensPlacement {
  return { cx: point.x, cy: point.y - offset };
}

export interface BoardDart {
  id: string;
  hit: Hit;
  pos?: Point;
  /** Dimmed, for darts from earlier visits. */
  past?: boolean;
}

export interface DartboardProps {
  onHit?: (hit: Hit, pos: Point) => void;
  darts?: BoardDart[];
  /** Drawn as a ring, to show where a checkout route says to aim. */
  target?: Hit | null;
  disabled?: boolean;
  /**
   * Drawn as a picture and nothing else: no taps, no lens, nothing for a
   * screen reader. The landing page uses it as its backdrop, where its size
   * and motion come from the element around it.
   */
  decorative?: boolean;
}

export function Dartboard({
  onHit,
  darts = [],
  target = null,
  disabled = false,
  decorative = false,
}: DartboardProps) {
  const beds = useMemo(buildBeds, []);
  const numbers = useMemo(
    () =>
      SECTORS.map((sector) => {
        const angle = rad(sectorAngle(sector));
        const r = (BOARD.doubleOuterRadius + BOARD.boardRadius) / 2;
        return {
          sector,
          x: r * Math.cos(angle),
          y: -r * Math.sin(angle),
        };
      }),
    [],
  );

  // Ids have to be unique per instance: two boards on one page would otherwise
  // share a lens clip and magnify each other.
  const uid = useId().replace(/:/g, '');
  const artId = `board-${uid}`;
  const dartsId = `darts-${uid}`;
  const clipId = `lens-${uid}`;

  const svgRef = useRef<SVGSVGElement>(null);
  const [preview, setPreview] = useState<{ pos: Point; hit: Hit } | null>(null);

  const positionOf = (event: ReactPointerEvent<SVGSVGElement>): Point | null => {
    const svg = svgRef.current;
    if (!svg) return null;

    const rect = svg.getBoundingClientRect();
    const size = Math.min(rect.width, rect.height);
    if (size === 0) return null;

    // The viewBox is square and centred on the bull, so screen → board is a
    // scale and a y flip.
    const originX = rect.left + (rect.width - size) / 2;
    const originY = rect.top + (rect.height - size) / 2;
    return {
      x: ((event.clientX - originX) / size) * 2 * R - R,
      y: -(((event.clientY - originY) / size) * 2 * R - R),
    };
  };

  const track = (event: ReactPointerEvent<SVGSVGElement>) => {
    if (disabled || !onHit) return;
    const pos = positionOf(event);
    if (!pos) return;

    const hit = scoreAt(pos);
    setPreview((current) => {
      // A short tick whenever the score under the finger changes: on a phone
      // that lands before the eye has read the lens.
      const changed =
        current === null || current.hit.value !== hit.value || current.hit.ring !== hit.ring;
      if (changed) navigator.vibrate?.(6);
      return { pos, hit };
    });
  };

  const commit = (event: ReactPointerEvent<SVGSVGElement>) => {
    if (disabled || !onHit) return;
    const pos = positionOf(event) ?? preview?.pos;
    setPreview(null);
    if (!pos) return;
    onHit(scoreAt(pos), pos);
  };

  const targetPos = target && target.ring !== 'miss' ? targetPoint(target) : null;

  const dartMarkers = darts.map((dart, index) =>
    dart.pos ? (
      <g key={dart.id} opacity={dart.past ? 0.35 : 1}>
        <circle cx={dart.pos.x} cy={-dart.pos.y} r={7} fill={COLOURS.marker} stroke={COLOURS.ink} strokeWidth={2} />
        <text
          x={dart.pos.x}
          y={-dart.pos.y + 4}
          fill={COLOURS.ink}
          fontSize={11}
          fontWeight={700}
          textAnchor="middle"
        >
          {index + 1}
        </text>
      </g>
    ) : null,
  );

  // The finger's point and the lens, both in SVG coordinates.
  const finger = preview ? { x: preview.pos.x, y: -preview.pos.y } : null;
  const lens = finger ? placeLens(finger) : null;
  const lensTransform =
    finger && lens
      ? `translate(${lens.cx} ${lens.cy}) scale(${LENS.magnification}) translate(${-finger.x} ${-finger.y})`
      : '';

  return (
    <svg
      ref={svgRef}
      className={decorative ? undefined : 'dartboard'}
      viewBox={`${-R} ${-R} ${2 * R} ${2 * R}`}
      role={decorative ? undefined : onHit ? 'button' : 'img'}
      aria-label={decorative ? undefined : 'Dartboard'}
      aria-hidden={decorative || undefined}
      onPointerDown={(event) => {
        if (decorative) return;
        event.currentTarget.setPointerCapture(event.pointerId);
        track(event);
      }}
      onPointerMove={(event) => {
        if (preview) track(event);
      }}
      onPointerUp={commit}
      onPointerCancel={() => setPreview(null)}
    >
      <defs>
        <g id={artId}>
          <circle cx={0} cy={0} r={R} fill={COLOURS.surround} />
          <g stroke={COLOURS.wire} strokeWidth={0.8}>
            {beds.map((b) => (
              <path key={b.key} d={b.d} fill={b.fill} />
            ))}
            <circle cx={0} cy={0} r={BOARD.outerBullRadius} fill={COLOURS.green} />
            <circle cx={0} cy={0} r={BOARD.bullRadius} fill={COLOURS.red} />
          </g>
          {/* A backdrop turns: numbers going round upside down are noise. */}
          {!decorative && (
            <g fill={COLOURS.number} fontSize={26} fontWeight={600} textAnchor="middle">
              {numbers.map((n) => (
                <text key={n.sector} x={n.x} y={n.y + 9}>
                  {n.sector}
                </text>
              ))}
            </g>
          )}
        </g>

        <g id={dartsId}>{dartMarkers}</g>

        {lens && (
          <clipPath id={clipId}>
            <circle cx={lens.cx} cy={lens.cy} r={LENS.radius} />
          </clipPath>
        )}
      </defs>

      <use href={`#${artId}`} />

      {targetPos && (
        <circle
          className="dartboard-target"
          cx={targetPos.x}
          cy={-targetPos.y}
          r={9}
          fill="none"
          stroke={COLOURS.ink}
          strokeWidth={2.5}
        />
      )}

      <use href={`#${dartsId}`} />

      {preview && finger && lens && (
        <g className="dartboard-lens" pointerEvents="none">
          {/* Where the finger actually is, left visible under the lens. */}
          <circle cx={finger.x} cy={finger.y} r={12} fill="none" stroke={COLOURS.ink} strokeWidth={1.6} opacity={0.9} />
          <circle cx={finger.x} cy={finger.y} r={2} fill={COLOURS.ink} />

          <circle
            cx={lens.cx}
            cy={lens.cy}
            r={LENS.radius + 3}
            fill={COLOURS.surround}
            stroke={COLOURS.ink}
            strokeWidth={3}
          />

          <g clipPath={`url(#${clipId})`}>
            <use href={`#${artId}`} transform={lensTransform} />
            <use href={`#${dartsId}`} transform={lensTransform} />

            {/* The crosshair sits at the lens centre, which is the finger's
                exact point magnified — the whole purpose of the thing. */}
            <g stroke={COLOURS.ink} strokeWidth={1.8} opacity={0.95}>
              <line x1={lens.cx - LENS.radius} y1={lens.cy} x2={lens.cx - 9} y2={lens.cy} />
              <line x1={lens.cx + 9} y1={lens.cy} x2={lens.cx + LENS.radius} y2={lens.cy} />
              <line x1={lens.cx} y1={lens.cy - LENS.radius} x2={lens.cx} y2={lens.cy - 9} />
              <line x1={lens.cx} y1={lens.cy + 9} x2={lens.cx} y2={lens.cy + LENS.radius} />
            </g>
            <circle cx={lens.cx} cy={lens.cy} r={3.5} fill="none" stroke={COLOURS.ink} strokeWidth={1.8} />

            <rect
              x={lens.cx - 34}
              y={lens.cy + LENS.radius - 30}
              width={68}
              height={26}
              rx={8}
              fill={COLOURS.plate}
            />
            <text
              x={lens.cx}
              y={lens.cy + LENS.radius - 11}
              fill={COLOURS.ink}
              fontSize={19}
              fontWeight={700}
              textAnchor="middle"
            >
              {formatHit(preview.hit)}
            </text>
          </g>
        </g>
      )}
    </svg>
  );
}
