// apps/web/src/components/GameCamera.vue
<!--
  The camera during a game, and the report.

  With the camera on, every settled throw is photographed and handed to the
  game visit (game/gameVisit.ts), which keeps the visit photo and, with
  "autoscorer scores" on, has it read for a new dart. When a score is wrong,
  the report opens the visit photo and asks the one question worth asking:
  where did the dart actually land? The answer corrects the score *and*
  becomes a labelled training example from exactly the setup and lighting that
  caused the mistake, which is the flywheel docs/03 is built around.
-->
<script setup lang="ts">
import { assessBoardView, boardRegion, formatHit, type Hit, type Point } from '@treblewise/core';
import { computed, ref, shallowRef, watch } from 'vue';
import { useRouter } from 'vue-router';

import { unlockCaller } from '../caller/caller.js';
import { unlockSounds } from '../caller/sounds.js';
import { raw, useExternal } from '../composables/external.js';
import { useCamera } from '../composables/useCamera.js';
import type { GameVisit } from '../game/gameVisit.js';
import { openReport, saveReport, type OpenedReport } from '../game/report.js';
import { fill, useStrings } from '../i18n/index.js';
import { PATHS } from '../router/paths.js';
import { putFrame, readDart } from '../storage/frames.js';
import { useLobbyStore, useSettingsStore } from '../store/stores.js';
import { cameraSupported, type GrabbedFrame } from '../vision/camera.js';
import { squareAround } from '../vision/crop.js';
import BoardOverlay from './BoardOverlay.vue';
import PhoneBattery from './PhoneBattery.vue';
import PhotoStage from './PhotoStage.vue';
import SetupCoach from './SetupCoach.vue';
import Toggle from './ui/Toggle.vue';

const props = defineProps<{
  matchId: string;
  /** The game visit: handed every photograph, and the visit whose darts a report marks. */
  gameVisit: GameVisit;
  /** Someone is to throw: the match is on and not won. */
  canThrow: boolean;
  /** The photograph the game visit's report is open on, or null: the game decides when one opens. */
  report: GrabbedFrame | null;
}>();

const emit = defineEmits<{
  /** "Report" pressed here: the game opens one, if it can be. */
  report: [];
  /** The report is done with, saved or cancelled. */
  closeReport: [];
  correct: [dartId: string, hit: Hit, pos: Point];
}>();

function newId(): string {
  return typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? crypto.randomUUID()
    : `frame-${Math.random().toString(36).slice(2)}-${Date.now()}`;
}

const t = useStrings();
const router = useRouter();
const settings = useSettingsStore();
const lobby = useLobbyStore();

const visitState = useExternal(props.gameVisit);
const darts = computed(() => visitState.value.visit?.darts ?? []);
const visitComplete = computed(() => visitState.value.visit?.complete === true);
const calibration = computed(() => settings.settings.calibration);
const keepFrames = computed({
  get: () => settings.settings.keepFrames,
  set: (on: boolean) => settings.setKeepFrames(on),
});
const autoscore = computed(() => settings.settings.autoscoreGames);
const modelInfo = computed(() => visitState.value.model.manifest);
const modelReady = computed(() => visitState.value.model.status === 'ready');

const latest = shallowRef<GrabbedFrame | null>(null);
/** The report on screen: the photograph it was opened on, its object URL, and its marks. */
const opened = shallowRef<{ photo: GrabbedFrame; url: string } | null>(null);
const report = shallowRef<OpenedReport | null>(null);
const saved = ref<string | null>(null);
// During a game the preview is clutter: the coach line says whether the
// camera is happy, and that is all anyone needs mid-leg. It is one tap away
// when something looks wrong.
const showPreview = ref(false);

// ---- the autoscorer -------------------------------------------------------
// The game visit drives the board watcher; the camera only switches the model
// on and off with the setting, and says what it is doing.
watch(keepFrames, (on) => on && void props.gameVisit.findModel(), { immediate: true });
// Only with frames kept: the camera is off otherwise, and the runtime is not
// worth fetching for nothing.
watch([keepFrames, autoscore], ([on, scoring]) => void props.gameVisit.switchModel(on && scoring), { immediate: true });
watch(
  () => visitState.value.model.status,
  (status) => {
    if (status === 'unavailable') settings.setAutoscoreGames(false); // it cannot run here: say so by switching back off
  },
);

// The capture trigger looks only at the board (see vision/settle.ts).
const region = computed(() => {
  const c = calibration.value;
  return c && c.width > 0 ? boardRegion(c.toImage, { width: c.width, height: c.height }) : null;
});
const reference = computed(() => (calibration.value?.reference ? Uint8Array.from(calibration.value.reference) : null));

const camera = useCamera({
  active: keepFrames,
  onSettle(frame, thumbnail, before) {
    latest.value = raw(frame);
    props.gameVisit.settle(frame, thumbnail, before);
  },
  captureOnSettle: true,
  region,
  reference,
  stream: () => (lobby.mode === 'paired' ? lobby.remoteStream : null),
  grab: () => {
    const pairing = lobby.pairing;
    return lobby.mode === 'paired' && pairing ? () => pairing.requestPhoto() : null;
  },
  // While a report is open nothing is photographed: a new photograph redrew
  // the card under the finger placing a marker, and flickered.
  paused: () => props.report !== null,
});

// A dart entered by hand has no photograph of its own: it was not read, so
// most likely it did not change the picture enough to be photographed (one
// hidden behind another, say). Take one now, so the report shows it.
let newestSeen: string | undefined;
watch(
  () => visitState.value.visit,
  () => {
    const newest = darts.value.at(-1);
    if (!newest || newest.id === newestSeen) return;
    newestSeen = newest.id;
    if (newest.source === 'auto' || !keepFrames.value || !camera.ready.value) return;
    void camera.capture().then((photo) => {
      if (!photo || newestSeen !== newest.id) return;
      latest.value = raw(photo);
      props.gameVisit.photographed(photo);
    });
  },
);

const view = computed(() =>
  calibration.value
    ? assessBoardView(calibration.value.toImage, { width: calibration.value.width, height: calibration.value.height })
    : null,
);

const usable = computed(
  () =>
    calibration.value !== null &&
    latest.value !== null &&
    calibration.value.width === latest.value.width &&
    calibration.value.height === latest.value.height,
);

// The game opens a report on a photograph, which stays fixed for as long as the
// report is open. The darts and the calibration are read as they are then.
watch(
  () => props.report,
  (photo, _, onCleanup) => {
    if (!photo || !calibration.value) return;
    const url = URL.createObjectURL(photo.jpeg);
    opened.value = { photo, url };
    report.value = openReport(darts.value, calibration.value);
    onCleanup(() => URL.revokeObjectURL(url));
  },
);
const shown = computed(() => (props.report !== null && opened.value?.photo === props.report ? props.report : null));

function closeReport() {
  opened.value = null;
  report.value = null;
  emit('closeReport');
}

async function save() {
  const photo = shown.value;
  const marks = report.value;
  if (!photo || !marks || !calibration.value) return;
  const result = saveReport({
    report: marks,
    darts: darts.value,
    photo,
    calibration: calibration.value,
    matchId: props.matchId,
    modelName: modelInfo.value?.name ?? null,
    id: newId(),
    ts: Date.now(),
  });
  if (result.frame) await putFrame(result.frame);
  for (const correction of result.corrections) emit('correct', correction.dartId, correction.hit, correction.pos);

  const labelled = marks.marks.filter((mark) => mark !== null);
  saved.value = [
    result.corrections.length > 0
      ? fill(t.report.scoreChanged, { score: labelled.map((mark) => formatHit(mark!.hit)).join(' ') })
      : result.frame
        ? t.report.saved
        : '',
    result.frame ? '' : t.report.notKept,
  ]
    .filter(Boolean)
    .join(' ');
  setTimeout(() => (saved.value = null), 4000);
  closeReport();
}

function setMark(index: number, mark: ReturnType<typeof readDart> | null) {
  const current = report.value;
  if (!current) return;
  report.value = { ...current, marks: current.marks.map((m, i) => (i === index ? mark : m)) };
}

const visibleMarks = computed(() =>
  (report.value?.marks ?? [])
    .map((mark, index) => ({ mark, index }))
    .filter((entry): entry is { mark: NonNullable<typeof entry.mark>; index: number } => entry.mark !== null),
);

function moveMark(visibleIndex: number, point: Point) {
  const target = visibleMarks.value[visibleIndex]?.index;
  if (target === undefined || !calibration.value) return;
  setMark(target, readDart(calibration.value, point));
}

function tapMark(point: Point) {
  if (!calibration.value || !report.value) return;
  const next = report.value.marks.findIndex((mark) => mark === null);
  if (next >= 0) setMark(next, readDart(calibration.value, point));
}

function toggleAutoscore() {
  unlockCaller();
  unlockSounds();
  settings.setAutoscoreGames(!autoscore.value);
}

const size = computed(() => ({ width: camera.width.value || 1280, height: camera.height.value || 720 }));
const reportCrop = computed(() =>
  shown.value && region.value && calibration.value?.width === shown.value.width ? squareAround(region.value, shown.value) : null,
);
const previewToImage = computed(() =>
  calibration.value && calibration.value.width === camera.width.value && calibration.value.height === camera.height.value
    ? calibration.value.toImage
    : null,
);
const supported = cameraSupported();
const attachVideo = (element: unknown) => {
  camera.video.value = element as HTMLVideoElement | null;
};
</script>

<template>
  <div v-if="supported" class="game-camera">
    <div class="controls">
      <Toggle v-model="keepFrames" :label="keepFrames ? t.report.cameraOn : t.report.cameraOff" />
      <button
        v-if="keepFrames"
        type="button"
        :class="visitComplete && usable && darts.length > 0 ? 'primary' : 'chip'"
        :disabled="!usable || darts.length === 0"
        @click="emit('report')"
      >
        {{ visitComplete ? t.report.markVisit : t.report.button }}
      </button>
      <button v-if="keepFrames" type="button" class="chip" @click="router.push(`${PATHS.camera}?from=game`)">
        {{ calibration ? t.report.cameraSetup : t.capture.calibrate }}
      </button>
      <Toggle v-if="keepFrames && calibration" v-model="showPreview" :label="t.report.preview" />
    </div>

    <div v-if="keepFrames && calibration && modelInfo" class="controls">
      <button
        type="button"
        :class="['chip', { 'chip-on': autoscore }]"
        :aria-pressed="autoscore"
        :disabled="!canThrow && !autoscore"
        @click="toggleAutoscore"
      >
        {{ autoscore ? (modelReady ? t.report.autoscoreOn : t.report.autoscoreLoading) : t.report.autoscoreOff }}
      </button>
    </div>
    <p v-if="keepFrames && calibration && modelInfo && autoscore" class="hint">
      {{ visitState.pullingOut ? t.report.autoscorePullOut : visitState.reading ? t.report.autoscoreReading : t.report.autoscoreHelp }}
      {{ fill(t.capture.modelName, { name: modelInfo.name }) }} {{ t.report.autoscoreUnchecked }}
      <template v-if="modelInfo.deepdarts">{{ ` ${t.capture.deepdartsCredit}` }}</template>
      <template v-if="modelInfo.dartscribe">{{ ` ${t.capture.dartscribeCredit}` }}</template>
    </p>

    <p v-if="saved" class="hint">{{ saved }}</p>

    <PhoneBattery v-if="keepFrames" />

    <SetupCoach v-if="keepFrames && camera.ready.value" :calibrated="calibration !== null" :view="view" :quality="camera.quality.value" />

    <div
      v-if="keepFrames"
      :class="['game-camera-preview', { 'game-camera-preview-hidden': !showPreview }]"
      :style="{
        aspectRatio: `${size.width} / ${size.height}`,
        // Cap the height by capping the width instead: clamping the height of
        // an aspect-ratio box squashes the picture.
        maxWidth: `calc(30vh * ${(size.width / size.height).toFixed(4)})`,
      }"
    >
      <video :ref="attachVideo" class="stage-video" playsinline muted />
      <BoardOverlay :width="size.width" :height="size.height" :to-image="previewToImage" />
      <div class="stage-badge">
        {{ camera.moving.value ? t.capture.moving : t.capture.waiting }}{{ latest ? ` · ${t.capture.captured}` : '' }}
      </div>
    </div>

    <p v-if="keepFrames && !usable && latest !== null" class="hint">{{ t.capture.noCalibration }}</p>
    <p v-if="keepFrames && latest === null" class="hint">{{ t.report.noFrame }}</p>

    <div v-if="opened && shown && report" class="overlay overlay-report" role="dialog" :aria-label="t.report.title">
      <div class="report">
        <div class="report-side">
          <h2>{{ t.report.title }}</h2>
          <p class="hint">{{ t.report.help }}</p>

          <div class="chip-row">
            <button v-for="(dart, index) in darts" :key="dart.id" type="button" class="chip" @click="setMark(index, null)">
              {{ index + 1 }}: {{ formatHit(dart.hit) }}{{
                report.marks[index] && report.marks[index]!.hit.value !== dart.hit.value ? ` → ${formatHit(report.marks[index]!.hit)}` : ''
              }}
            </button>
          </div>

          <div class="controls">
            <button type="button" class="primary" @click="save">{{ t.report.save }}</button>
            <button type="button" class="chip" @click="closeReport">{{ t.report.cancel }}</button>
          </div>
        </div>

        <PhotoStage
          class="report-board"
          :url="opened.url"
          :width="shown.width"
          :height="shown.height"
          :crop="reportCrop"
          :to-image="calibration?.toImage ?? null"
          :darts="visibleMarks.map(({ mark, index }) => ({ img: mark.img, label: `${index + 1} · ${formatHit(mark.hit)}` }))"
          :on-dart-move="moveMark"
          :on-tap="tapMark"
        />
      </div>
    </div>
  </div>
</template>

// apps/web/src/components/GameCamera.tsx
/**
 * The camera during a game, and the report flow.
 *
 * With the camera on, every settled throw is photographed and the latest frame
 * is held in memory. When a score is wrong — today because a finger slipped,
 * later because the autoscorer read it wrong — "Report" opens that photograph
 * and asks the one question worth asking: where did the dart actually land?
 *
 * The answer corrects the score *and* becomes a labelled training example from
 * exactly the setup and lighting that caused the mistake, which is the flywheel
 * `docs/03` is built around.
 *
 * With "autoscorer scores" on, each settled photograph is also read by the tip
 * model the way the capture lab reads it (vision/boardWatcher.ts), and a new dart
 * goes straight into the score as an 'auto' dart and is called. The player
 * corrects a wrong one by tapping it, and the correction keeps the model's
 * reading as the original, which is the agreement measure docs/03 asks for.
 * After a visit the darts have to come out first: until the board looks empty
 * again (or the next dart is entered by hand) nothing is read.
 */

import { assessBoardView, boardRegion, formatHit, type DartSource, type Hit, type Point } from '@treblewise/core';
import { useEffect, useMemo, useRef, useState } from 'react';

import { fill, useStrings } from '../i18n/index.js';
import {
  projectToImage,
  putFrame,
  readDart,
  type CapturedFrame,
  type LabelledDart,
} from '../storage/frames.js';
import { useMatchStore } from '../store/match.js';
import { unlockCaller } from '../caller/caller.js';
import { unlockSounds } from '../caller/sounds.js';
import type { BoardDart } from '../vision/boardWatcher.js';
import { cameraSupported, type GrabbedFrame } from '../vision/camera.js';
import { squareAround } from '../vision/crop.js';
import { useBoardWatcher } from '../vision/useBoardWatcher.js';
import { useCamera } from '../vision/useCamera.js';
import { BoardOverlay } from './BoardOverlay.js';
import { PhoneBattery } from './PhoneBattery.js';
import { PhotoStage } from './PhotoStage.js';
import { SetupCoach } from './SetupCoach.js';

export interface ReportableDart {
  id: string;
  hit: Hit;
  pos?: Point;
  /** How it was entered: a dart the autoscorer did not read is photographed when it is entered. */
  source?: DartSource;
}

export interface GameCameraProps {
  matchId: string;
  /** The darts of the visit on the board right now. */
  darts: ReportableDart[];
  /** True once the visit is thrown: the moment to mark where they landed. */
  visitComplete: boolean;
  /** The darts above belong to the visit being thrown now, not the last one. */
  visitInProgress: boolean;
  /** The game says the finished visit's darts are out ("Darts out" was pressed): stop waiting for them. */
  visitClosed: boolean;
  /** Someone is to throw: the match is on and not won. */
  canThrow: boolean;
  onCorrect: (dartId: string, hit: Hit, pos: Point) => void;
  /** The autoscorer read a new dart. */
  onAutoDart: (hit: Hit, pos: Point, confidence: number) => void;
  /** The darts came out with `remaining` of the visit unthrown: those missed the board. */
  onDartsPulled: (remaining: number) => void;
  /** The darts of a finished visit came out: the next player is up. */
  onTurnPassed: () => void;
  /** Opens the report when it changes: the game's own "Mark where they landed", beside the dart being corrected. */
  reportRequests?: number;
  /** Whether a report can be opened now (a photograph of this visit, a calibration that fits it). */
  onReportAvailable?: (available: boolean) => void;
}

function newId(): string {
  return typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? crypto.randomUUID()
    : `frame-${Math.random().toString(36).slice(2)}-${Date.now()}`;
}

export function GameCamera({
  matchId,
  darts,
  visitComplete,
  visitInProgress,
  visitClosed,
  canThrow,
  onCorrect,
  onAutoDart,
  onDartsPulled,
  onTurnPassed,
  reportRequests = 0,
  onReportAvailable,
}: GameCameraProps) {
  const t = useStrings();
  const keepFrames = useMatchStore((s) => s.settings.keepFrames);
  const setKeepFrames = useMatchStore((s) => s.setKeepFrames);
  const calibration = useMatchStore((s) => s.settings.calibration);
  const openCameraSetup = useMatchStore((s) => s.openCameraSetup);
  const mode = useMatchStore((s) => s.mode);
  const remoteStream = useMatchStore((s) => s.remoteStream);
  const pairing = useMatchStore((s) => s.pairing);

  const [latest, setLatest] = useState<GrabbedFrame | null>(null);
  const [reporting, setReporting] = useState(false);
  const [frameUrl, setFrameUrl] = useState<string | null>(null);
  const [marks, setMarks] = useState<(LabelledDart | null)[]>([]);
  /**
   * The marks the report opened with for darts tapped on the drawn board: a
   * point on a drawing, not the tip in the photograph. Left where they are,
   * the photograph is kept but waits in Review to be confirmed. Moving one
   * replaces it with a person's mark, which is no longer in this set.
   */
  const boardPlaced = useRef(new WeakSet<LabelledDart>());
  const [saved, setSaved] = useState<string | null>(null);
  // During a game the preview is clutter: the coach line says whether the
  // camera is happy, and that is all anyone needs mid-leg. It is one tap away
  // when something looks wrong.
  const [showPreview, setShowPreview] = useState(false);
  const latestRef = useRef<GrabbedFrame | null>(null);
  /**
   * The visit photo: the photograph taken when the visit's latest dart went
   * in. The report shows this one, not the newest: by the time someone reports
   * a dart, the newest photograph is often a hand pulling the darts out. And a
   * new photograph is compared with it for what changed, for the same reason:
   * the newest settle may be a hand reaching in, which would hide the dart
   * that came after it.
   */
  const visitFrameRef = useRef<GrabbedFrame | null>(null);
  const visitKey = useRef<{ first: string | undefined; count: number }>({ first: undefined, count: 0 });
  useEffect(() => {
    const first = darts[0]?.id;
    const seen = visitKey.current;
    if (first !== seen.first || darts.length > seen.count) visitFrameRef.current = latestRef.current;
    visitKey.current = { first, count: darts.length };
  }, [darts]);
  /** The photograph a report is open on: fixed for as long as it is open. */
  const [shown, setShown] = useState<GrabbedFrame | null>(null);

  // ---- the autoscorer -----------------------------------------------------
  // What the board shows between settles, and reading a photograph for a new
  // dart, is the board watcher's (vision/boardWatcher.ts). The game tells it
  // what it knows and decides what a settle means for the score.
  const autoscore = useMatchStore((s) => s.settings.autoscoreGames);
  const setAutoscore = useMatchStore((s) => s.setAutoscoreGames);
  const { watcher, state: watched } = useBoardWatcher();
  const modelInfo = watched.model.manifest;
  const modelReady = watched.model.status === 'ready';

  useEffect(() => {
    watcher.setCalibration(calibration);
  }, [watcher, calibration]);

  // The darts in the board are the visit's while it is being thrown. Once it
  // is over they are still there, but nothing is read beside them: the
  // pull-out phase comes first.
  useEffect(() => {
    watcher.holds((visitInProgress ? darts : []).map((dart): BoardDart => (dart.pos ? { board: dart.pos } : {})));
    watcher.setVisitPhoto(visitFrameRef.current);
  }, [watcher, darts, visitInProgress]);

  // A finished visit leaves its darts in the board until someone pulls them,
  // unless they were seen coming out before it ended; a dart of the next
  // visit means they are out, which the watcher sees in the darts it holds.
  const lastVisitDone = visitComplete && darts.length > 0 && !visitInProgress;
  useEffect(() => {
    if (lastVisitDone) watcher.visitOver();
  }, [watcher, lastVisitDone]);
  // Only during the pull-out phase: a visit closed by the next one's first
  // dart already holds that dart, which "darts out" would forget.
  useEffect(() => {
    if (visitClosed && watcher.state().pullingOut) watcher.dartsOut();
  }, [watcher, visitClosed]);

  useEffect(() => {
    if (keepFrames) void watcher.findModel();
  }, [watcher, keepFrames]);
  // Only with frames kept: the camera is off otherwise, and the runtime is
  // not worth fetching for nothing.
  useEffect(() => {
    void watcher.switchModel(keepFrames && autoscore);
  }, [watcher, keepFrames, autoscore]);
  useEffect(() => {
    if (watched.model.status === 'unavailable') setAutoscore(false); // it cannot run here: say so by switching back off
  }, [watched.model.status, setAutoscore]);

  const read = async (frame: GrabbedFrame) => {
    const reading = await watcher.read(frame);
    if (reading.kind !== 'proposal') return;
    // A reading takes a while. A dart entered by hand meanwhile makes it stale
    // (the watcher says so); the autoscorer switched off is checked here.
    if (!useMatchStore.getState().settings.autoscoreGames || !canThrow) return;
    onAutoDart(reading.dart.hit, reading.dart.board, reading.dart.confidence);
  };

  // useCamera calls the latest of these, so the props it reads are current.
  const onSettle = (frame: GrabbedFrame, thumbnail?: Uint8Array, before?: Uint8Array | null) => {
    latestRef.current = frame;
    setLatest(frame);
    if (!autoscore || !modelReady || !canThrow) return;

    const seen = watcher.settle(frame, thumbnail, before);
    if (seen.kind === 'emptied') onTurnPassed();
    else if (seen.kind === 'early-pull') onDartsPulled(seen.missed);
    else if (seen.kind === 'throw') void read(frame);
  };

  // The capture trigger looks only at the board — see vision/settle.ts.
  const region = useMemo(
    () =>
      calibration && calibration.width > 0
        ? boardRegion(calibration.toImage, { width: calibration.width, height: calibration.height })
        : null,
    [calibration],
  );

  const reference = useMemo(
    () => (calibration?.reference ? Uint8Array.from(calibration.reference) : null),
    [calibration],
  );

  const camera = useCamera({
    active: keepFrames,
    onSettle,
    captureOnSettle: true,
    region,
    reference,
    stream: mode === 'paired' ? remoteStream : null,
    grab: mode === 'paired' && pairing ? () => pairing.requestPhoto() : null,
    // While a report is open nothing is photographed: a new photograph
    // re-rendered the card under the finger placing a marker, and flickered.
    paused: reporting,
  });

  // A dart entered by hand has no photograph of its own: it was not read, so
  // most likely it did not change the picture enough to be photographed (one
  // hidden behind another, say). Take one now, so the report shows it.
  const newestSeen = useRef<string | undefined>(undefined);
  useEffect(() => {
    const newest = darts.at(-1);
    if (!newest || newest.id === newestSeen.current) return;
    newestSeen.current = newest.id;
    if (newest.source === 'auto' || !keepFrames || !camera.ready) return;
    void camera.capture().then((photo) => {
      if (!photo || newestSeen.current !== newest.id) return;
      latestRef.current = photo;
      setLatest(photo);
      visitFrameRef.current = photo;
      watcher.setVisitPhoto(photo);
    });
    // The camera object changes every render; only a new dart matters.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [darts]);

  const view = useMemo(
    () =>
      calibration
        ? assessBoardView(calibration.toImage, { width: calibration.width, height: calibration.height })
        : null,
    [calibration],
  );

  const usable =
    calibration !== null &&
    latest !== null &&
    calibration.width === latest.width &&
    calibration.height === latest.height;

  const canReport = keepFrames && usable && darts.length > 0;
  useEffect(() => {
    onReportAvailable?.(canReport);
  }, [canReport, onReportAvailable]);

  // The game asks for a report by bumping the counter.
  const reportsSeen = useRef(reportRequests);
  useEffect(() => {
    if (reportRequests === reportsSeen.current) return;
    reportsSeen.current = reportRequests;
    if (canReport && !reporting) openReport();
    // openReport is this render's; the request is what triggers it.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reportRequests]);

  const openReport = () => {
    const photo =
      visitFrameRef.current && calibration && visitFrameRef.current.width === calibration.width
        ? visitFrameRef.current
        : latest;
    if (!photo || !calibration) return;
    const url = URL.createObjectURL(photo.jpeg);
    setShown(photo);
    setFrameUrl(url);
    // Pre-place a marker wherever a dart already has a position: correcting a
    // marker that is nearly right is much faster than placing three.
    boardPlaced.current = new WeakSet();
    setMarks(
      darts.map((dart) => {
        if (!dart.pos || !usable) return null;
        const mark: LabelledDart = {
          img: projectToImage(calibration, dart.pos),
          board: dart.pos,
          hit: dart.hit,
          // The autoscorer's own reading stays the model's until a person
          // moves it, so the trainer never grades the model against itself.
          ...(dart.source === 'auto' ? { by: 'model' as const } : {}),
        };
        if (dart.source !== 'auto') boardPlaced.current.add(mark);
        return mark;
      }),
    );
    setReporting(true);
  };

  const closeReport = () => {
    if (frameUrl) URL.revokeObjectURL(frameUrl);
    setFrameUrl(null);
    setShown(null);
    setReporting(false);
    setMarks([]);
  };

  const saveReport = async () => {
    const latest = shown;
    if (!latest || !calibration) return;

    const labelled = marks.filter((mark): mark is LabelledDart => mark !== null);
    // A photograph is only a training example if every dart of the visit has a
    // mark on it. A dart entered on the keypad has no position, and left
    // unmarked it would teach the model that a dart it can see is background.
    const complete = darts.length > 0 && marks.length === darts.length && labelled.length === darts.length;
    const byModel = labelled.some((mark) => mark.by === 'model');
    // Marks a person placed or moved here, and the autoscorer's let stand, are
    // accepted as they are; a drawn-board tap left unmoved waits in Review.
    const confirmed = !labelled.some((mark) => boardPlaced.current.has(mark));
    const frame: CapturedFrame = {
      id: newId(),
      ts: Date.now(),
      source: 'game',
      matchId,
      width: latest.width,
      height: latest.height,
      jpeg: latest.jpeg,
      calibration: {
        imagePoints: calibration.imagePoints,
        toImage: calibration.toImage,
        toBoard: calibration.toBoard,
        error: calibration.error,
        width: calibration.width,
        height: calibration.height,
      },
      darts: labelled,
      labelled: labelled.length > 0,
      ...(byModel && modelInfo ? { model: modelInfo.name } : {}),
      ...(confirmed ? { reviewed: true } : {}),
      reported: {
        hits: darts.map((dart) => formatHit(dart.hit)),
        dartIds: darts.map((dart) => dart.id),
        source: 'manual',
      },
    };
    if (complete) await putFrame(frame);

    // Anything whose score moved is corrected in the match as well, kept or not.
    let corrections = 0;
    marks.forEach((mark, index) => {
      const dart = darts[index];
      if (!mark || !dart) return;
      if (mark.hit.value === dart.hit.value && mark.hit.ring === dart.hit.ring) return;
      onCorrect(dart.id, mark.hit, mark.board);
      corrections += 1;
    });

    setSaved(
      [
        corrections > 0
          ? fill(t.report.scoreChanged, { score: labelled.map((mark) => formatHit(mark.hit)).join(' ') })
          : complete
            ? t.report.saved
            : '',
        complete ? '' : t.report.notKept,
      ]
        .filter(Boolean)
        .join(' '),
    );
    setTimeout(() => setSaved(null), 4000);
    closeReport();
  };

  useEffect(() => () => {
    if (frameUrl) URL.revokeObjectURL(frameUrl);
  }, [frameUrl]);

  if (!cameraSupported()) return null;

  const size = { width: camera.width || 1280, height: camera.height || 720 };
  const reportCrop =
    shown && region && calibration?.width === shown.width ? squareAround(region, shown) : null;

  return (
    <div className="game-camera">
      <div className="controls">
        <button
          type="button"
          className={`chip${keepFrames ? ' chip-on' : ''}`}
          onClick={() => setKeepFrames(!keepFrames)}
        >
          {keepFrames ? t.report.cameraOn : t.report.cameraOff}
        </button>
        {keepFrames && (
          <button
            type="button"
            className={visitComplete && usable && darts.length > 0 ? 'primary' : 'chip'}
            onClick={openReport}
            disabled={!usable || darts.length === 0}
          >
            {visitComplete ? t.report.markVisit : t.report.button}
          </button>
        )}
        {keepFrames && (
          <button type="button" className="chip" onClick={openCameraSetup}>
            {calibration ? t.report.cameraSetup : t.capture.calibrate}
          </button>
        )}
        {keepFrames && calibration && (
          <button
            type="button"
            className={`chip${showPreview ? ' chip-on' : ''}`}
            onClick={() => setShowPreview((on) => !on)}
          >
            {t.report.preview}
          </button>
        )}
      </div>

      {keepFrames && calibration && modelInfo && (
        <div className="controls">
          <button
            type="button"
            className={`chip${autoscore ? ' chip-on' : ''}`}
            onClick={() => {
              unlockCaller();
              unlockSounds();
              setAutoscore(!autoscore);
            }}
            disabled={!canThrow && !autoscore}
          >
            {autoscore ? (modelReady ? t.report.autoscoreOn : t.report.autoscoreLoading) : t.report.autoscoreOff}
          </button>
        </div>
      )}
      {keepFrames && calibration && modelInfo && autoscore && (
        <p className="hint">
          {watched.pullingOut ? t.report.autoscorePullOut : watched.reading ? t.report.autoscoreReading : t.report.autoscoreHelp}{' '}
          {fill(t.capture.modelName, { name: modelInfo.name })} {t.report.autoscoreUnchecked}
          {modelInfo.deepdarts && ` ${t.capture.deepdartsCredit}`}
          {modelInfo.dartscribe && ` ${t.capture.dartscribeCredit}`}
        </p>
      )}

      {saved && <p className="hint">{saved}</p>}

      {keepFrames && <PhoneBattery />}

      {keepFrames && camera.ready && (
        <SetupCoach calibrated={calibration !== null} view={view} quality={camera.quality} />
      )}

      {keepFrames && (
        <div
          className={`game-camera-preview${showPreview ? '' : ' game-camera-preview-hidden'}`}
          style={{
            aspectRatio: `${size.width} / ${size.height}`,
            // Cap the height by capping the width instead: clamping the height
            // of an aspect-ratio box squashes the picture, which is what this
            // preview used to do.
            maxWidth: `calc(30vh * ${(size.width / size.height).toFixed(4)})`,
          }}
        >
          <video ref={camera.videoRef} className="stage-video" playsInline muted />
          <BoardOverlay
            width={size.width}
            height={size.height}
            toImage={
              calibration && calibration.width === camera.width && calibration.height === camera.height
                ? calibration.toImage
                : null
            }
          />
          <div className="stage-badge">
            {camera.moving ? t.capture.moving : t.capture.waiting}
            {latest ? ` · ${t.capture.captured}` : ''}
          </div>
        </div>
      )}

      {keepFrames && !usable && latest !== null && <p className="hint">{t.capture.noCalibration}</p>}
      {keepFrames && latest === null && <p className="hint">{t.report.noFrame}</p>}

      {reporting && frameUrl && shown && (
        <div className="overlay overlay-report" role="dialog" aria-label={t.report.title}>
          <div className="report">
            <div className="report-side">
              <h2>{t.report.title}</h2>
              <p className="hint">{t.report.help}</p>

              <div className="chip-row">
                {darts.map((dart, index) => {
                  const mark = marks[index];
                  return (
                    <button
                      key={dart.id}
                      type="button"
                      className="chip"
                      onClick={() => setMarks((current) => current.map((m, i) => (i === index ? null : m)))}
                    >
                      {index + 1}: {formatHit(dart.hit)}
                      {mark && mark.hit.value !== dart.hit.value ? ` → ${formatHit(mark.hit)}` : ''}
                    </button>
                  );
                })}
              </div>

              <div className="controls">
                <button type="button" className="primary" onClick={() => void saveReport()}>
                  {t.report.save}
                </button>
                <button type="button" className="chip" onClick={closeReport}>
                  {t.report.cancel}
                </button>
              </div>
            </div>

            <PhotoStage
              className="report-board"
              url={frameUrl}
              width={shown.width}
              height={shown.height}
              crop={reportCrop}
              toImage={calibration?.toImage ?? null}
              darts={marks
                .map((mark, index) => ({ mark, index }))
                .filter(({ mark }) => mark !== null)
                .map(({ mark, index }) => ({
                  img: mark!.img,
                  label: `${index + 1} · ${formatHit(mark!.hit)}`,
                }))}
              onDartMove={(visibleIndex, point) => {
                if (!calibration) return;
                const indices = marks.map((mark, index) => (mark ? index : -1)).filter((index) => index >= 0);
                const target = indices[visibleIndex];
                if (target === undefined) return;
                setMarks((current) =>
                  current.map((mark, index) => (index === target ? readDart(calibration, point) : mark)),
                );
              }}
              onTap={(point) => {
                if (!calibration) return;
                const next = marks.findIndex((mark) => mark === null);
                if (next < 0) return;
                setMarks((current) =>
                  current.map((mark, index) => (index === next ? readDart(calibration, point) : mark)),
                );
              }}
            />
          </div>
        </div>
      )}
    </div>
  );
}
