// apps/web/src/components/Scoreboard.tsx
/**
 * The scoreboard. Read from two or three metres away in bad light, so the
 * remaining score is the biggest thing on the screen and everything else is
 * deliberately quiet.
 */

import { formatRoute, matchStats, type MatchSnapshot } from '@treblewise/core';

import { useStrings } from '../i18n/index.js';

export interface ScoreboardProps {
  snapshot: MatchSnapshot;
  /**
   * The player whose finished visit is still in the board: shown as the one
   * at the oche until the darts come out, although the score has moved on.
   */
  holding?: string | null;
}

export function Scoreboard({ snapshot, holding = null }: ScoreboardProps) {
  const t = useStrings();
  const stats = matchStats(snapshot);
  const current = snapshot.current;
  const leg = snapshot.legs.at(-1);
  const showSets = snapshot.config.setsToWin > 1;

  return (
    <div className="scoreboard">
      {snapshot.config.players.map((player) => {
        const isCurrent = holding ? holding === player.id : current?.playerId === player.id;
        const isNext = !holding && current?.playerId === player.id;
        // Once a leg is won, every card shows the next leg's start score: the
        // won leg's zero (and the loser's remainder) belongs to the history,
        // not to the board everyone is about to throw at.
        const legOver = leg?.winnerId != null;
        const remaining = isNext
          ? current!.remaining
          : legOver
            ? snapshot.config.startScore
            : leg?.remaining[player.id] ?? snapshot.config.startScore;
        const playerStats = stats[player.id]!;
        const visit = [...(leg?.visits ?? [])].reverse().find((v) => v.playerId === player.id);

        return (
          <div key={player.id} className={`player${isCurrent ? ' player-current' : ''}`}>
            <div className="player-head">
              <span className="player-name">{player.name}</span>
              <span className="player-counts">
                {showSets && (
                  <span title={t.game.sets}>
                    {t.game.sets} {snapshot.setsWon[player.id] ?? 0}
                  </span>
                )}
                <span title={t.game.legs}>
                  {t.game.legs} {snapshot.legsWon[player.id] ?? 0}
                </span>
              </span>
            </div>

            <div className="player-remaining">{remaining}</div>

            {isNext && current!.checkout && (
              <div className="player-checkout" title={t.game.chartNote}>
                {formatRoute(current!.checkout)}
              </div>
            )}

            <div className="player-meta">
              <span>
                {t.game.average} <b>{playerStats.average.toFixed(1)}</b>
              </span>
              <span>
                {t.game.darts} <b>{playerStats.dartsThrown}</b>
              </span>
              {playerStats.checkoutPercent !== null && (
                <span>
                  {t.game.checkoutPercent} <b>{playerStats.checkoutPercent.toFixed(0)}%</b>
                </span>
              )}
            </div>

            <div className="player-visit">
              {visit
                ? visit.busted
                  ? t.game.busted
                  : visit.darts.map((d) => d.hit.value).join(' · ')
                : ' '}
            </div>
          </div>
        );
      })}
    </div>
  );
}

// apps/web/src/components/Scoreboard.vue
<!--
  The scoreboard. Read from two or three metres away in bad light, so the
  remaining score is the biggest thing on the screen and everything else is
  deliberately quiet.
-->
<script setup lang="ts">
import { formatRoute, matchStats, type MatchSnapshot } from '@treblewise/core';
import { computed } from 'vue';

import { useStrings } from '../i18n/index.js';

const props = withDefaults(
  defineProps<{
    snapshot: MatchSnapshot;
    /**
     * The player whose finished visit is still in the board: shown as the one
     * at the oche until the darts come out, although the score has moved on.
     */
    holding?: string | null;
  }>(),
  { holding: null },
);

const t = useStrings();

const cards = computed(() => {
  const { snapshot, holding } = props;
  const stats = matchStats(snapshot);
  const current = snapshot.current;
  const leg = snapshot.legs.at(-1);
  // Once a leg is won, every card shows the next leg's start score: the won
  // leg's zero (and the loser's remainder) belongs to the history, not to the
  // board everyone is about to throw at.
  const legOver = leg?.winnerId != null;
  return snapshot.config.players.map((player) => {
    const isNext = !holding && current?.playerId === player.id;
    const visit = [...(leg?.visits ?? [])].reverse().find((v) => v.playerId === player.id);
    return {
      player,
      isCurrent: holding ? holding === player.id : current?.playerId === player.id,
      remaining: isNext ? current!.remaining : legOver ? snapshot.config.startScore : (leg?.remaining[player.id] ?? snapshot.config.startScore),
      checkout: isNext && current!.checkout ? formatRoute(current!.checkout) : null,
      stats: stats[player.id]!,
      visit: visit ? (visit.busted ? t.game.busted : visit.darts.map((d) => d.hit.value).join(' · ')) : ' ',
    };
  });
});
</script>

<template>
  <div class="scoreboard">
    <div v-for="card in cards" :key="card.player.id" :class="['player', { 'player-current': card.isCurrent }]">
      <div class="player-head">
        <span class="player-name">{{ card.player.name }}</span>
        <span class="player-counts">
          <span v-if="snapshot.config.setsToWin > 1" :title="t.game.sets">{{ t.game.sets }} {{ snapshot.setsWon[card.player.id] ?? 0 }}</span>
          <span :title="t.game.legs">{{ t.game.legs }} {{ snapshot.legsWon[card.player.id] ?? 0 }}</span>
        </span>
      </div>

      <div class="player-remaining">{{ card.remaining }}</div>

      <div v-if="card.checkout" class="player-checkout" :title="t.game.chartNote">{{ card.checkout }}</div>

      <div class="player-meta">
        <span>{{ t.game.average }} <b>{{ card.stats.average.toFixed(1) }}</b></span>
        <span>{{ t.game.darts }} <b>{{ card.stats.dartsThrown }}</b></span>
        <span v-if="card.stats.checkoutPercent !== null">
          {{ t.game.checkoutPercent }} <b>{{ card.stats.checkoutPercent.toFixed(0) }}%</b>
        </span>
      </div>

      <div class="player-visit">{{ card.visit }}</div>
    </div>
  </div>
</template>
