// apps/web/src/screens/Game.tsx
import { formatHit, formatRoute, type Hit, type Point } from '@treblewise/core';
import { useEffect, useState } from 'react';

import { Dartboard, type BoardDart } from '../components/Dartboard.js';
import { GameCamera } from '../components/GameCamera.js';
import { Keypad } from '../components/Keypad.js';
import { Scoreboard } from '../components/Scoreboard.js';
import { unlockCaller } from '../caller/caller.js';
import { playThud, playTurn, unlockSounds } from '../caller/sounds.js';
import { useGameVisit } from '../game/useGameVisit.js';
import { fill, useStrings } from '../i18n/index.js';
import { useMatchStore } from '../store/match.js';
import type { GrabbedFrame } from '../vision/camera.js';

export function Game() {
  const t = useStrings();
  const snapshot = useMatchStore((s) => s.snapshot);
  const match = useMatchStore((s) => s.match);
  const settings = useMatchStore((s) => s.settings);
  const throwDart = useMatchStore((s) => s.throwDart);
  const correctDart = useMatchStore((s) => s.correctDart);
  const undo = useMatchStore((s) => s.undo);
  const toggleCaller = useMatchStore((s) => s.toggleCaller);
  const toggleSounds = useMatchStore((s) => s.toggleSounds);
  const setEntryMode = useMatchStore((s) => s.setEntryMode);
  const setScreen = useMatchStore((s) => s.setScreen);
  const goHome = useMatchStore((s) => s.goHome);
  const session = useMatchStore((s) => s.session);

  /** id of the dart being corrected, if any. */
  const [correcting, setCorrecting] = useState<string | null>(null);
  /** The photograph the game visit's report is open on: the game decides when, the camera shows it. */
  const [reportOn, setReportOn] = useState<GrabbedFrame | null>(null);

  // Which visit's darts are in the board, and where it stands, is the game
  // visit's (game/gameVisit.ts); so is what the camera sees of it.
  const autoscoring = settings.keepFrames && settings.autoscoreGames;
  const { gameVisit, state: gameVisitState } = useGameVisit({
    snapshot,
    autoscoring,
    calibration: settings.calibration,
  });

  // The game visit says when the autoscorer entered a dart and when the turn
  // passes; the sounds are the game's.
  useEffect(
    () =>
      gameVisit.listen((signal) => {
        if (!useMatchStore.getState().settings.soundsEnabled) return;
        if (signal === 'dart-read') playThud();
        else playTurn();
      }),
    [gameVisit],
  );

  if (!snapshot) return null;

  const current = snapshot.current;
  const finished = snapshot.winnerId !== null;

  // The visit being thrown, or between visits the one just thrown, so its
  // darts stay on the board until the next player throws: a player walking
  // back from the board should still see where their darts landed.
  const { visit, position } = gameVisitState;
  const visitIsCurrent = position === 'throwing';
  // The visit just thrown, for as long as it is correctable here.
  const lastVisit = position === 'open' || position === 'held' ? visit : null;
  // Held, with the autoscorer scoring: the screen stays on the player who just
  // threw until the darts come out. The next player is not at the oche yet,
  // and the finished visit is the one anyone looks at to check it. The score
  // itself has moved on; only what is shown waits.
  const held = position === 'held';
  const nameOf = (id: string) => snapshot.config.players.find((p) => p.id === id)?.name ?? '';

  const canReport = settings.keepFrames && gameVisitState.reportable;
  const openReport = () => {
    if (canReport && !reportOn && gameVisitState.photo) setReportOn(gameVisitState.photo);
  };

  const dartChip = (dart: { id: string; hit: Hit; source: string }) => (
    <button
      key={dart.id}
      type="button"
      className={`dart-chip${correcting === dart.id ? ' dart-chip-correcting' : ''}${
        dart.source === 'auto' ? ' dart-chip-auto' : ''
      }`}
      onClick={() => setCorrecting((id) => (id === dart.id ? null : dart.id))}
      title={t.game.correctingHint}
    >
      {formatHit(dart.hit)}
    </button>
  );

  const visitDarts: BoardDart[] = (visit?.darts ?? []).map((dart) => ({
    id: dart.id,
    hit: dart.hit,
    ...(dart.pos ? { pos: dart.pos } : {}),
    past: !visitIsCurrent,
  }));

  const record = (hit: Hit, pos?: Point) => {
    unlockCaller();
    unlockSounds();
    if (correcting) {
      correctDart(correcting, hit, pos);
      setCorrecting(null);
      return;
    }
    if (settings.soundsEnabled) playThud();
    throwDart(hit, pos ? { pos } : {});
  };

  const winnerName =
    snapshot.config.players.find((p) => p.id === snapshot.winnerId)?.name ?? snapshot.winnerId ?? '';

  return (
    <div className="screen screen-game">
      <Scoreboard snapshot={snapshot} holding={held ? lastVisit!.playerId : null} />

      {held && lastVisit && current && (
        <div className="throw-strip throw-strip-held">
          <span className="throw-who">{fill(t.game.pullOut, { name: nameOf(lastVisit.playerId) })}</span>
          <span className="throw-darts">{lastVisit.darts.map(dartChip)}</span>
          {/* One row, always the same height: while a dart of this visit is
              being corrected, "Mark where they landed" takes its place beside
              "Darts out" instead of being searched for further down. */}
          <div className="held-actions">
            <button type="button" className="primary darts-out" onClick={() => gameVisit.dartsOut()}>
              {fill(t.game.dartsOut, { name: nameOf(current.playerId) })}
            </button>
            {correcting && canReport && lastVisit.darts.some((dart) => dart.id === correcting) && (
              <button
                type="button"
                className="chip held-mark"
                onClick={() => {
                  setCorrecting(null);
                  openReport();
                }}
              >
                {t.report.markVisit}
              </button>
            )}
          </div>
        </div>
      )}

      {current && !held && (
        <div className="throw-strip">
          <span className="throw-who">
            {snapshot.config.players.find((p) => p.id === current.playerId)?.name} {t.game.toThrow}
          </span>
          <span className="throw-darts">
            {(visitIsCurrent ? visit?.darts ?? [] : []).map(dartChip)}
            {Array.from({ length: visitIsCurrent ? Math.max(0, 3 - (visit?.darts.length ?? 0)) : 3 }).map((_, index) => (
              <span key={`empty-${index}`} className="dart-chip dart-chip-empty">
                ·
              </span>
            ))}
          </span>
        </div>
      )}

      {position === 'open' && lastVisit && (
        <div className="throw-strip throw-strip-last">
          <span className="throw-who">
            {fill(t.game.lastVisit, {
              name: snapshot.config.players.find((p) => p.id === lastVisit.playerId)?.name ?? '',
            })}
          </span>
          <span className="throw-darts">{lastVisit.darts.map(dartChip)}</span>
        </div>
      )}
      {correcting && <p className="hint">{t.game.correctingHint}</p>}

      <div className="entry">
        {settings.entryMode === 'board' ? (
          <Dartboard
            onHit={record}
            darts={visitDarts}
            target={held ? null : current?.checkout?.[visitIsCurrent ? visit?.darts.length ?? 0 : 0] ?? null}
            disabled={finished}
          />
        ) : (
          <Keypad onHit={(hit) => record(hit)} disabled={finished} />
        )}
      </div>

      {current?.checkout && !held && (
        <p className="checkout-line" title={t.game.chartNote}>
          {t.game.checkout}: <b>{formatRoute(current.checkout)}</b>
        </p>
      )}

      <div className="controls">
        <button type="button" className="chip" onClick={undo}>
          {t.game.undo}
        </button>
        <button
          type="button"
          className={`chip${settings.callerEnabled ? ' chip-on' : ''}`}
          onClick={toggleCaller}
        >
          {settings.callerEnabled ? t.game.callerOn : t.game.callerOff}
        </button>
        <button
          type="button"
          className={`chip${settings.soundsEnabled ? ' chip-on' : ''}`}
          onClick={() => {
            unlockSounds();
            toggleSounds();
          }}
        >
          {settings.soundsEnabled ? t.game.soundsOn : t.game.soundsOff}
        </button>
        <button
          type="button"
          className="chip"
          onClick={() => setEntryMode(settings.entryMode === 'board' ? 'keypad' : 'board')}
        >
          {settings.entryMode === 'board' ? t.game.keypad : t.game.board}
        </button>
        <button type="button" className="chip" onClick={() => setScreen('stats')}>
          {t.stats.title}
        </button>
        <button type="button" className="chip" onClick={() => setScreen('setup')}>
          {t.game.newMatch}
        </button>
        {session && (
          <button type="button" className="chip" onClick={goHome}>
            {t.lobby.back}
          </button>
        )}
      </div>

      {settings.entryMode === 'board' && !finished && <p className="hint">{t.game.sourceNote}</p>}

      {match && (
        <GameCamera
          matchId={match.id}
          gameVisit={gameVisit}
          canThrow={current !== null && !finished}
          report={reportOn}
          onReport={openReport}
          onCloseReport={() => setReportOn(null)}
          onCorrect={(dartId, hit, pos) => correctDart(dartId, hit, pos)}
        />
      )}

      {finished && (
        <div className="overlay">
          <div className="overlay-card">
            <h2>{fill(t.game.matchWon, { name: winnerName })}</h2>
            <button type="button" className="primary" onClick={() => setScreen('setup')}>
              {t.game.newMatch}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

// apps/web/src/screens/Game.vue
<!--
  The match in play: the scoreboard, who is at the oche and their darts, the
  board or the keypad to enter them, and the camera.

  Which visit's darts are in the board, and where it stands (throwing, open,
  held or closed), is the game visit's (game/gameVisit.ts); so is what the
  camera sees of it. The screen shows it, plays its sounds, and owns whether a
  report is open.
-->
<script setup lang="ts">
import { formatRoute, type Hit, type Point } from '@treblewise/core';
import { computed, onScopeDispose, ref, shallowRef } from 'vue';
import { useRouter } from 'vue-router';

import { unlockCaller } from '../caller/caller.js';
import { playThud, playTurn, unlockSounds } from '../caller/sounds.js';
import Dartboard, { type BoardDart } from '../components/Dartboard.vue';
import GameCamera from '../components/GameCamera.vue';
import Keypad from '../components/Keypad.vue';
import Scoreboard from '../components/Scoreboard.vue';
import ThrowStrip from '../components/ui/ThrowStrip.vue';
import Toggle from '../components/ui/Toggle.vue';
import { useGameVisit } from '../composables/useGameVisit.js';
import { fill, useStrings } from '../i18n/index.js';
import { PATHS } from '../router/paths.js';
import { useLobbyStore, useMatchesStore, useSettingsStore } from '../store/stores.js';
import type { GrabbedFrame } from '../vision/camera.js';

const t = useStrings();
const router = useRouter();
const matches = useMatchesStore();
const settings = useSettingsStore();
const lobby = useLobbyStore();

/** id of the dart being corrected, if any. */
const correcting = ref<string | null>(null);
/** The photograph the game visit's report is open on: the game decides when, the camera shows it. */
const reportOn = shallowRef<GrabbedFrame | null>(null);

const autoscoring = computed(() => settings.settings.keepFrames && settings.settings.autoscoreGames);
const { gameVisit, state: visitState } = useGameVisit({
  snapshot: () => matches.snapshot,
  autoscoring,
  calibration: () => settings.settings.calibration,
});

// The game visit says when the autoscorer entered a dart and when the turn
// passes; the sounds are the game's.
onScopeDispose(
  gameVisit.listen((signal) => {
    if (!settings.settings.soundsEnabled) return;
    if (signal === 'dart-read') playThud();
    else playTurn();
  }),
);

const snapshot = computed(() => matches.snapshot);
const current = computed(() => snapshot.value?.current ?? null);
const finished = computed(() => snapshot.value?.winnerId != null);

// The visit being thrown, or between visits the one just thrown, so its darts
// stay on the board until the next player throws: a player walking back from
// the board should still see where their darts landed.
const visit = computed(() => visitState.value.visit);
const position = computed(() => visitState.value.position);
const visitIsCurrent = computed(() => position.value === 'throwing');
// The visit just thrown, for as long as it is correctable here.
const lastVisit = computed(() => (position.value === 'open' || position.value === 'held' ? visit.value : null));
// Held, with the autoscorer scoring: the screen stays on the player who just
// threw until the darts come out. The next player is not at the oche yet, and
// the finished visit is the one anyone looks at to check it. The score itself
// has moved on; only what is shown waits.
const held = computed(() => position.value === 'held');

const nameOf = (id: string) => snapshot.value?.config.players.find((p) => p.id === id)?.name ?? '';

const canReport = computed(() => settings.settings.keepFrames && visitState.value.reportable);
function openReport() {
  if (canReport.value && !reportOn.value && visitState.value.photo) reportOn.value = visitState.value.photo;
}

const pick = (id: string) => {
  correcting.value = correcting.value === id ? null : id;
};

const visitDarts = computed<BoardDart[]>(() =>
  (visit.value?.darts ?? []).map((dart) => ({
    id: dart.id,
    hit: dart.hit,
    ...(dart.pos ? { pos: dart.pos } : {}),
    past: !visitIsCurrent.value,
  })),
);

const target = computed(() =>
  held.value ? null : (current.value?.checkout?.[visitIsCurrent.value ? (visit.value?.darts.length ?? 0) : 0] ?? null),
);

function record(hit: Hit, pos?: Point) {
  unlockCaller();
  unlockSounds();
  if (correcting.value) {
    matches.correctDart(correcting.value, hit, pos);
    correcting.value = null;
    return;
  }
  if (settings.settings.soundsEnabled) playThud();
  matches.throwDart(hit, pos ? { pos } : {});
}

const callerOn = computed({ get: () => settings.settings.callerEnabled, set: () => settings.toggleCaller() });
const soundsOn = computed({
  get: () => settings.settings.soundsEnabled,
  set: () => {
    unlockSounds();
    settings.toggleSounds();
  },
});

const winnerName = computed(() => {
  const s = snapshot.value;
  return s ? (s.config.players.find((p) => p.id === s.winnerId)?.name ?? s.winnerId ?? '') : '';
});

function markVisit() {
  correcting.value = null;
  openReport();
}
</script>

<template>
  <div v-if="snapshot" class="screen screen-game">
    <Scoreboard :snapshot="snapshot" :holding="held && lastVisit ? lastVisit.playerId : null" />

    <ThrowStrip
      v-if="held && lastVisit && current"
      variant="held"
      :who="fill(t.game.pullOut, { name: nameOf(lastVisit.playerId) })"
      :darts="lastVisit.darts"
      :correcting="correcting"
      pickable
      :hint="t.game.correctingHint"
      @pick="pick"
    >
      <!-- One row, always the same height: while a dart of this visit is being
           corrected, "Mark where they landed" takes its place beside "Darts
           out" instead of being searched for further down. -->
      <template #actions>
        <div class="held-actions">
          <button type="button" class="primary darts-out" @click="gameVisit.dartsOut()">
            {{ fill(t.game.dartsOut, { name: nameOf(current.playerId) }) }}
          </button>
          <button
            v-if="correcting && canReport && lastVisit.darts.some((dart) => dart.id === correcting)"
            type="button"
            class="chip held-mark"
            @click="markVisit"
          >
            {{ t.report.markVisit }}
          </button>
        </div>
      </template>
    </ThrowStrip>

    <ThrowStrip
      v-if="current && !held"
      :who="`${nameOf(current.playerId)} ${t.game.toThrow}`"
      :darts="visitIsCurrent ? (visit?.darts ?? []) : []"
      :empty="visitIsCurrent ? Math.max(0, 3 - (visit?.darts.length ?? 0)) : 3"
      :correcting="correcting"
      pickable
      :hint="t.game.correctingHint"
      @pick="pick"
    />

    <ThrowStrip
      v-if="position === 'open' && lastVisit"
      variant="last"
      :who="fill(t.game.lastVisit, { name: nameOf(lastVisit.playerId) })"
      :darts="lastVisit.darts"
      :correcting="correcting"
      pickable
      :hint="t.game.correctingHint"
      @pick="pick"
    />
    <p v-if="correcting" class="hint">{{ t.game.correctingHint }}</p>

    <div class="entry">
      <Dartboard
        v-if="settings.settings.entryMode === 'board'"
        interactive
        :darts="visitDarts"
        :target="target"
        :disabled="finished"
        @hit="record"
      />
      <Keypad v-else :disabled="finished" @hit="(hit) => record(hit)" />
    </div>

    <p v-if="current?.checkout && !held" class="checkout-line" :title="t.game.chartNote">
      {{ t.game.checkout }}: <b>{{ formatRoute(current.checkout) }}</b>
    </p>

    <div class="controls">
      <button type="button" class="chip" @click="matches.undo()">{{ t.game.undo }}</button>
      <Toggle v-model="callerOn" :label="callerOn ? t.game.callerOn : t.game.callerOff" />
      <Toggle v-model="soundsOn" :label="soundsOn ? t.game.soundsOn : t.game.soundsOff" />
      <button
        type="button"
        class="chip"
        @click="settings.setEntryMode(settings.settings.entryMode === 'board' ? 'keypad' : 'board')"
      >
        {{ settings.settings.entryMode === 'board' ? t.game.keypad : t.game.board }}
      </button>
      <button type="button" class="chip" @click="router.push(PATHS.stats)">{{ t.stats.title }}</button>
      <button type="button" class="chip" @click="router.push(PATHS.setup)">{{ t.game.newMatch }}</button>
      <button v-if="lobby.session" type="button" class="chip" @click="router.push(PATHS.lobby)">{{ t.lobby.back }}</button>
    </div>

    <p v-if="settings.settings.entryMode === 'board' && !finished" class="hint">{{ t.game.sourceNote }}</p>

    <GameCamera
      v-if="matches.match"
      :match-id="matches.match.id"
      :game-visit="gameVisit"
      :can-throw="current !== null && !finished"
      :report="reportOn"
      @report="openReport"
      @close-report="reportOn = null"
      @correct="(dartId, hit, pos) => matches.correctDart(dartId, hit, pos)"
    />

    <div v-if="finished" class="overlay">
      <div class="overlay-card">
        <h2>{{ fill(t.game.matchWon, { name: winnerName }) }}</h2>
        <button type="button" class="primary" @click="router.push(PATHS.setup)">{{ t.game.newMatch }}</button>
      </div>
    </div>
  </div>
</template>
