// apps/web/src/screens/Review.tsx
/**
 * Review: the second look at every labelled photograph.
 *
 * Labels are made in a hurry, at the oche, between throws. This screen is where
 * they are checked sitting down: each photograph with its marks, whole and
 * undistorted, to fix, confirm or throw away. It exists because a training set
 * nobody can inspect is a training set nobody can trust — some of the first
 * photographs saved themselves, and some carry a model's guesses that landed on
 * the flight (issues #3, #5).
 *
 * A photograph confirmed here is recorded as `reviewed`, and that is exported.
 */

import { boardRegion, formatHit } from '@treblewise/core';
import { useCallback, useEffect, useMemo, useState } from 'react';

import { PhotoStage } from '../components/PhotoStage.js';
import { fill, useStrings } from '../i18n/index.js';
import { deleteFrame, listFrames, putFrame, readDart, type CapturedFrame, type LabelledDart } from '../storage/frames.js';
import { filterFrames, hasModelMarks, markedBy, modelsWithMarks, type ReviewFilter } from '../storage/review.js';
import { useMatchStore } from '../store/match.js';
import { squareAround } from '../vision/crop.js';

const PAGE = 12;

/**
 * The same marks, by value. Not by identity: every reload reads the
 * photographs back from IndexedDB as new objects, and comparing objects made
 * every photograph after the first one "changed", which disabled Previous,
 * Next and Back to the list.
 */
function sameMarks(a: readonly LabelledDart[], b: readonly LabelledDart[]): boolean {
  return (
    a.length === b.length &&
    a.every((dart, i) => {
      const other = b[i]!;
      return (
        dart.img.x === other.img.x &&
        dart.img.y === other.img.y &&
        dart.board.x === other.board.x &&
        dart.board.y === other.board.y &&
        dart.hit.ring === other.hit.ring &&
        dart.hit.value === other.hit.value &&
        dart.by === other.by
      );
    })
  );
}

/** The board's square in a stored photograph, from the calibration it was taken with. */
function reviewCrop(frame: CapturedFrame) {
  const size = { width: frame.width, height: frame.height };
  const region = boardRegion(frame.calibration.toImage, size);
  return region ? squareAround(region, size) : null;
}

export function Review() {
  const t = useStrings();
  const goHome = useMatchStore((s) => s.goHome);

  const [frames, setFrames] = useState<CapturedFrame[] | null>(null);
  const [filter, setFilter] = useState<ReviewFilter>('all');
  const [page, setPage] = useState(0);
  const [openId, setOpenId] = useState<string | null>(null);
  /** The marks as edited; saved back only by "Looks right". */
  const [marks, setMarks] = useState<LabelledDart[]>([]);
  const [confirm, setConfirm] = useState<string | null>(null);

  const reload = useCallback(async () => {
    setFrames(await listFrames(Number.MAX_SAFE_INTEGER));
  }, []);

  useEffect(() => {
    void reload();
  }, [reload]);

  const shown = useMemo(() => filterFrames(frames ?? [], filter), [frames, filter]);
  const pages = Math.max(1, Math.ceil(shown.length / PAGE));
  const current = Math.min(page, pages - 1);
  const visible = useMemo(() => shown.slice(current * PAGE, current * PAGE + PAGE), [shown, current]);
  const open = useMemo(() => (frames ?? []).find((frame) => frame.id === openId) ?? null, [frames, openId]);
  const models = useMemo(() => modelsWithMarks(frames ?? []), [frames]);

  // Object URLs only for what is on screen: a few hundred full-size JPEGs at
  // once is more memory than a phone has.
  const urls = useMemo(() => {
    const map = new Map<string, string>();
    for (const frame of open ? [open] : visible) map.set(frame.id, URL.createObjectURL(frame.jpeg));
    return map;
  }, [visible, open]);
  useEffect(() => () => urls.forEach((url) => URL.revokeObjectURL(url)), [urls]);

  const openFrame = (frame: CapturedFrame) => {
    setOpenId(frame.id);
    setMarks(frame.darts);
    setConfirm(null);
  };

  const dirty = open !== null && !sameMarks(marks, open.darts);

  /** The neighbour in the filtered list, to move through them without the list. */
  const neighbour = (step: 1 | -1): CapturedFrame | null => {
    if (!open) return null;
    const index = shown.findIndex((frame) => frame.id === open.id);
    return index < 0 ? null : (shown[index + step] ?? null);
  };

  const saveOpen = async () => {
    if (!open || marks.length === 0) return;
    const next = neighbour(1);
    const stillModel = marks.some((dart) => dart.by === 'model');
    const { model: _model, ...rest } = open;
    await putFrame({
      ...rest,
      darts: marks,
      labelled: true,
      reviewed: true,
      // Once no mark of the model's is left standing, the frame is a person's.
      ...(stillModel && open.model ? { model: open.model } : {}),
    });
    await reload();
    if (next) openFrame(next);
    else setOpenId(null);
  };

  const deleteOpen = async () => {
    if (!open) return;
    const next = neighbour(1) ?? neighbour(-1);
    await deleteFrame(open.id);
    await reload();
    if (next) openFrame(next);
    else setOpenId(null);
  };

  const deleteByModel = async (model: string) => {
    if (confirm !== `model:${model}`) {
      setConfirm(`model:${model}`);
      return;
    }
    setConfirm(null);
    await Promise.all(markedBy(frames ?? [], model).map((frame) => deleteFrame(frame.id)));
    await reload();
  };

  if (frames === null) return <div className="screen screen-review" />;

  if (open) {
    const url = urls.get(open.id);
    return (
      <div className="screen screen-review">
        <header className="screen-head">
          <h1>{t.review.title}</h1>
          <p>{t.review.detailHelp}</p>
        </header>

        {url && (
          <PhotoStage
            className="review-board"
            url={url}
            width={open.width}
            height={open.height}
            crop={reviewCrop(open)}
            toImage={open.calibration.toImage}
            darts={marks.map((dart, index) => ({
              img: dart.img,
              label: `${index + 1} · ${formatHit(dart.hit)}${dart.by === 'model' ? '?' : ''}`,
              kind: dart.by === 'model' ? ('proposed' as const) : ('new' as const),
            }))}
            onDartMove={(index, point) =>
              setMarks((list) => list.map((dart, i) => (i === index ? readDart(open.calibration, point) : dart)))
            }
            onTap={(point) => setMarks((list) => [...list, readDart(open.calibration, point)])}
          />
        )}

        <div className="chip-row">
          {marks.map((dart, index) => (
            <button
              key={index}
              type="button"
              className="chip"
              aria-label={fill(t.review.removeMark, { n: index + 1 })}
              onClick={() => setMarks((list) => list.filter((_, i) => i !== index))}
            >
              {index + 1} · {formatHit(dart.hit)}
              {dart.by === 'model' ? ` (${t.review.byModel})` : ''} ×
            </button>
          ))}
        </div>
        <p className="hint">
          {open.reviewed ? t.review.alreadyReviewed : t.review.notReviewed}
          {dirty ? ` ${t.review.unsaved}` : ''}
        </p>

        <div className="controls">
          <button type="button" className="primary" onClick={() => void saveOpen()} disabled={marks.length === 0}>
            {t.review.looksRight}
          </button>
          <button
            type="button"
            className="chip"
            onClick={() => (confirm === 'delete' ? void deleteOpen() : setConfirm('delete'))}
          >
            {confirm === 'delete' ? t.review.deleteConfirm : t.review.deletePhoto}
          </button>
          {dirty && (
            <button type="button" className="chip" onClick={() => setMarks(open.darts)}>
              {t.review.discard}
            </button>
          )}
        </div>

        <div className="screen-actions">
          <button type="button" className="chip" disabled={dirty || !neighbour(-1)} onClick={() => openFrame(neighbour(-1)!)}>
            {t.review.previous}
          </button>
          <button type="button" className="chip" disabled={dirty || !neighbour(1)} onClick={() => openFrame(neighbour(1)!)}>
            {t.review.next}
          </button>
          <button type="button" className="chip" disabled={dirty} onClick={() => setOpenId(null)}>
            {t.review.backToList}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="screen screen-review">
      <header className="screen-head">
        <h1>{t.review.title}</h1>
        <p>{fill(t.review.subtitle, { n: frames.length, reviewed: frames.filter((frame) => frame.reviewed).length })}</p>
      </header>

      <div className="chip-row">
        {(['all', 'unreviewed', 'model'] as const).map((value) => (
          <button
            key={value}
            type="button"
            className={`chip${filter === value ? ' chip-on' : ''}`}
            onClick={() => {
              setFilter(value);
              setPage(0);
            }}
          >
            {t.review.filters[value]} ({filterFrames(frames, value).length})
          </button>
        ))}
      </div>

      {models.length > 0 && (
        <section className="panel">
          <p className="hint">{t.review.modelHelp}</p>
          <div className="controls">
            {models.map(({ model, frames: count }) => (
              <button key={model} type="button" className="chip" onClick={() => void deleteByModel(model)}>
                {confirm === `model:${model}`
                  ? fill(t.review.deleteModelConfirm, { n: count })
                  : fill(t.review.deleteModel, { model, n: count })}
              </button>
            ))}
          </div>
        </section>
      )}

      {shown.length === 0 && <p className="hint">{t.review.empty}</p>}

      <ul className="review-grid">
        {visible.map((frame) => (
          <li key={frame.id}>
            <button type="button" className="review-card" onClick={() => openFrame(frame)}>
              <img src={urls.get(frame.id)} alt="" loading="lazy" style={{ aspectRatio: `${frame.width} / ${frame.height}` }} />
              <span className="review-card-line">
                {frame.darts.map((dart) => formatHit(dart.hit)).join(', ') || t.review.noMarks}
              </span>
              <span className="review-card-tags">
                {frame.source === 'game' ? t.review.fromGame : t.review.fromLab}
                {hasModelMarks(frame) ? ` · ${t.review.byModel}` : ''}
                {frame.reviewed ? ` · ${t.review.reviewedTag}` : ''}
              </span>
            </button>
          </li>
        ))}
      </ul>

      {pages > 1 && (
        <div className="controls">
          <button type="button" className="chip" disabled={current === 0} onClick={() => setPage(current - 1)}>
            {t.review.previous}
          </button>
          <span className="hint">{fill(t.review.page, { n: current + 1, of: pages })}</span>
          <button type="button" className="chip" disabled={current >= pages - 1} onClick={() => setPage(current + 1)}>
            {t.review.next}
          </button>
        </div>
      )}

      <div className="screen-actions">
        <button type="button" className="chip" onClick={goHome}>
          {t.review.back}
        </button>
      </div>
    </div>
  );
}

// apps/web/src/screens/Review.vue
<!--
  Review: the second look at every labelled photograph.

  Labels are made in a hurry, at the oche, between throws. This screen is where
  they are checked sitting down: each photograph with its marks, whole and
  undistorted, to fix, confirm or throw away. It exists because a training set
  nobody can inspect is a training set nobody can trust: some of the first
  photographs saved themselves, and some carry a model's guesses that landed on
  the flight (issues #3, #5).

  The list is at /review, each photograph at /review/:id, so one can be linked
  and reloaded into. A photograph confirmed here is recorded as `reviewed`, and
  that is exported.
-->
<script setup lang="ts">
import { boardRegion, formatHit } from '@treblewise/core';
import { computed, onMounted, ref, shallowRef, watch, watchEffect } from 'vue';
import { useRoute, useRouter } from 'vue-router';

import PhotoStage from '../components/PhotoStage.vue';
import ScreenShell from '../components/ui/ScreenShell.vue';
import Segmented from '../components/ui/Segmented.vue';
import { fill, useStrings } from '../i18n/index.js';
import { PATHS } from '../router/paths.js';
import { deleteFrame, listFrames, putFrame, readDart, type CapturedFrame, type LabelledDart } from '../storage/frames.js';
import { filterFrames, hasModelMarks, markedBy, modelsWithMarks, type ReviewFilter } from '../storage/review.js';
import { squareAround } from '../vision/crop.js';

const PAGE = 12;

/**
 * The same marks, by value. Not by identity: every reload reads the
 * photographs back from IndexedDB as new objects, and comparing objects made
 * every photograph after the first one "changed", which disabled Previous,
 * Next and Back to the list.
 */
function sameMarks(a: readonly LabelledDart[], b: readonly LabelledDart[]): boolean {
  return (
    a.length === b.length &&
    a.every((dart, i) => {
      const other = b[i]!;
      return (
        dart.img.x === other.img.x &&
        dart.img.y === other.img.y &&
        dart.board.x === other.board.x &&
        dart.board.y === other.board.y &&
        dart.hit.ring === other.hit.ring &&
        dart.hit.value === other.hit.value &&
        dart.by === other.by
      );
    })
  );
}

/** The board's square in a stored photograph, from the calibration it was taken with. */
function reviewCrop(frame: CapturedFrame) {
  const size = { width: frame.width, height: frame.height };
  const region = boardRegion(frame.calibration.toImage, size);
  return region ? squareAround(region, size) : null;
}

const t = useStrings();
const route = useRoute();
const router = useRouter();

const frames = shallowRef<CapturedFrame[] | null>(null);
const filter = ref<ReviewFilter>('all');
const page = ref(0);
/** The marks as edited; saved back only by "Looks right". */
const marks = shallowRef<LabelledDart[]>([]);
const confirm = ref<string | null>(null);

async function reload() {
  frames.value = await listFrames(Number.MAX_SAFE_INTEGER);
}
onMounted(reload);

const openId = computed(() => (typeof route.params.id === 'string' ? route.params.id : null));
const open = computed(() => (frames.value ?? []).find((frame) => frame.id === openId.value) ?? null);

// A photograph opens with its marks as stored.
watch(
  () => open.value?.id,
  () => {
    marks.value = open.value?.darts ?? [];
    confirm.value = null;
  },
  { immediate: true },
);

const shown = computed(() => filterFrames(frames.value ?? [], filter.value));
const pages = computed(() => Math.max(1, Math.ceil(shown.value.length / PAGE)));
const current = computed(() => Math.min(page.value, pages.value - 1));
const visible = computed(() => shown.value.slice(current.value * PAGE, current.value * PAGE + PAGE));
const models = computed(() => modelsWithMarks(frames.value ?? []));
const filterOptions = computed(() =>
  (['all', 'unreviewed', 'model'] as const).map((value) => ({
    value,
    label: `${t.review.filters[value]} (${filterFrames(frames.value ?? [], value).length})`,
  })),
);
watch(filter, () => (page.value = 0));

// Object URLs only for what is on screen: a few hundred full-size JPEGs at once
// is more memory than a phone has.
const urls = shallowRef(new Map<string, string>());
watchEffect((onCleanup) => {
  const map = new Map<string, string>();
  for (const frame of open.value ? [open.value] : visible.value) map.set(frame.id, URL.createObjectURL(frame.jpeg));
  urls.value = map;
  onCleanup(() => map.forEach((url) => URL.revokeObjectURL(url)));
});

const openFrame = (frame: CapturedFrame) => void router.push(`${PATHS.review}/${frame.id}`);
const backToList = () => void router.push(PATHS.review);

const dirty = computed(() => open.value !== null && !sameMarks(marks.value, open.value.darts));

/** The neighbour in the filtered list, to move through them without the list. */
function neighbour(step: 1 | -1): CapturedFrame | null {
  if (!open.value) return null;
  const index = shown.value.findIndex((frame) => frame.id === open.value!.id);
  return index < 0 ? null : (shown.value[index + step] ?? null);
}

async function saveOpen() {
  const frame = open.value;
  if (!frame || marks.value.length === 0) return;
  const next = neighbour(1);
  const stillModel = marks.value.some((dart) => dart.by === 'model');
  const { model: _model, ...rest } = frame;
  await putFrame({
    ...rest,
    darts: marks.value,
    labelled: true,
    reviewed: true,
    // Once no mark of the model's is left standing, the frame is a person's.
    ...(stillModel && frame.model ? { model: frame.model } : {}),
  });
  await reload();
  if (next) openFrame(next);
  else backToList();
}

async function deleteOpen() {
  const frame = open.value;
  if (!frame) return;
  const next = neighbour(1) ?? neighbour(-1);
  await deleteFrame(frame.id);
  await reload();
  if (next) openFrame(next);
  else backToList();
}

async function deleteByModel(model: string) {
  if (confirm.value !== `model:${model}`) {
    confirm.value = `model:${model}`;
    return;
  }
  confirm.value = null;
  await Promise.all(markedBy(frames.value ?? [], model).map((frame) => deleteFrame(frame.id)));
  await reload();
}

function moveMark(index: number, point: { x: number; y: number }) {
  const frame = open.value;
  if (frame) marks.value = marks.value.map((dart, i) => (i === index ? readDart(frame.calibration, point) : dart));
}
function addMark(point: { x: number; y: number }) {
  const frame = open.value;
  if (frame) marks.value = [...marks.value, readDart(frame.calibration, point)];
}
const removeMark = (index: number) => {
  marks.value = marks.value.filter((_, i) => i !== index);
};
const reviewDarts = computed(() =>
  marks.value.map((dart, index) => ({
    img: dart.img,
    label: `${index + 1} · ${formatHit(dart.hit)}${dart.by === 'model' ? '?' : ''}`,
    kind: dart.by === 'model' ? ('proposed' as const) : ('new' as const),
  })),
);
</script>

<template>
  <div v-if="frames === null" class="screen screen-review" />

  <ScreenShell
    v-else-if="openId"
    name="review"
    :title="t.review.title"
    :lead="open ? t.review.detailHelp : t.review.missing"
    :back-label="t.review.backToList"
    :back-disabled="dirty"
    :on-back="backToList"
  >
    <template v-if="open">
      <PhotoStage
        v-if="urls.get(open.id)"
        class="review-board"
        :url="urls.get(open.id)!"
        :width="open.width"
        :height="open.height"
        :crop="reviewCrop(open)"
        :to-image="open.calibration.toImage"
        :darts="reviewDarts"
        :on-dart-move="moveMark"
        :on-tap="addMark"
      />

      <div class="chip-row">
        <button
          v-for="(dart, index) in marks"
          :key="index"
          type="button"
          class="chip"
          :aria-label="fill(t.review.removeMark, { n: index + 1 })"
          @click="removeMark(index)"
        >
          {{ index + 1 }} · {{ formatHit(dart.hit) }}{{ dart.by === 'model' ? ` (${t.review.byModel})` : '' }} ×
        </button>
      </div>
      <p class="hint">{{ open.reviewed ? t.review.alreadyReviewed : t.review.notReviewed }}{{ dirty ? ` ${t.review.unsaved}` : '' }}</p>

      <div class="controls">
        <button type="button" class="primary" :disabled="marks.length === 0" @click="saveOpen">{{ t.review.looksRight }}</button>
        <button type="button" class="chip" @click="confirm === 'delete' ? deleteOpen() : (confirm = 'delete')">
          {{ confirm === 'delete' ? t.review.deleteConfirm : t.review.deletePhoto }}
        </button>
        <button v-if="dirty" type="button" class="chip" @click="marks = open.darts">{{ t.review.discard }}</button>
      </div>
    </template>

    <template #actions>
      <button type="button" class="chip" :disabled="dirty || !neighbour(-1)" @click="openFrame(neighbour(-1)!)">{{ t.review.previous }}</button>
      <button type="button" class="chip" :disabled="dirty || !neighbour(1)" @click="openFrame(neighbour(1)!)">{{ t.review.next }}</button>
    </template>
  </ScreenShell>

  <ScreenShell
    v-else
    name="review"
    :title="t.review.title"
    :lead="fill(t.review.subtitle, { n: frames.length, reviewed: frames.filter((frame) => frame.reviewed).length })"
    :back-label="t.review.back"
  >
    <Segmented v-model="filter" :options="filterOptions" :label="t.review.filterLabel" />

    <section v-if="models.length > 0" class="panel">
      <p class="hint">{{ t.review.modelHelp }}</p>
      <div class="controls">
        <button v-for="{ model, frames: count } in models" :key="model" type="button" class="chip" @click="deleteByModel(model)">
          {{ confirm === `model:${model}` ? fill(t.review.deleteModelConfirm, { n: count }) : fill(t.review.deleteModel, { model, n: count }) }}
        </button>
      </div>
    </section>

    <p v-if="shown.length === 0" class="hint">{{ t.review.empty }}</p>

    <ul class="review-grid">
      <li v-for="frame in visible" :key="frame.id">
        <button type="button" class="review-card" @click="openFrame(frame)">
          <img :src="urls.get(frame.id)" alt="" loading="lazy" :style="{ aspectRatio: `${frame.width} / ${frame.height}` }" />
          <span class="review-card-line">{{ frame.darts.map((dart) => formatHit(dart.hit)).join(', ') || t.review.noMarks }}</span>
          <span class="review-card-tags">
            {{ frame.source === 'game' ? t.review.fromGame : t.review.fromLab }}{{ hasModelMarks(frame) ? ` · ${t.review.byModel}` : ''
            }}{{ frame.reviewed ? ` · ${t.review.reviewedTag}` : '' }}
          </span>
        </button>
      </li>
    </ul>

    <div v-if="pages > 1" class="controls">
      <button type="button" class="chip" :disabled="current === 0" @click="page = current - 1">{{ t.review.previous }}</button>
      <span class="hint">{{ fill(t.review.page, { n: current + 1, of: pages }) }}</span>
      <button type="button" class="chip" :disabled="current >= pages - 1" @click="page = current + 1">{{ t.review.next }}</button>
    </div>
  </ScreenShell>
</template>
